import 'package:flutter/material.dart';

class ColorResources {
  static const Color COLOR_PRIMARY = Color(0xff387AF6);
  static const Color COLOR_LANGUAGE = Color(0xff426A7C);
  static const Color COLOR_ENGLISH = Color(0xff4039C3);
  static const Color COLOR_RED = Color(0xffDB1B56);
  static const Color COLOR_HINDI = Color(0xff03D191);
  static const Color COLOR_BANGLA = Color(0xffFCFBF7);
  static const Color BACKGROUND = Color(0xffE3EDF6);
  static const Color COLOR_DODGER_BLUE = Color(0xff0086FC);
  static const Color COLOR_MAYA_BLUE = Color(0xff5CADFF);
  static const Color COLOR_ROYAL_BLUE = Color(0xff4D49E1);
  static const Color COLOR_PRIMARY_DARK = Color(0xff4D49E1);
  static const Color COLOR_BLACK = Color(0xff000000);
  static const Color COLOR_GRAY = Color(0xff707070);
  static const Color COLOR_CHARCOAL = Color(0xff474747);
  static const Color COLOR_DIM_GRAY = Color(0xff6D6D6D);
  static const Color COLOR_VERY_LIGHT_GRAY = Color(0xffD8DBC8);
  static const Color COLOR_WHITE_GRAY = Color(0xffE6E6E6);
  static const Color COLOR_GHOST_WHITE = Color(0xffF2F2FF);
  static const Color COLOR_HAWKES_BLUE = Color(0xffF7F6FB);
  static const Color COLOR_WHITE_SMOKE = Color(0xffEDEDED);
  static const Color COLOR_SILVER = Color(0xffC4C4C4);
  static const Color COLOR_GAINSBORO = Color(0xffE8E8E8);
  static const Color COLOR_WHITE = Color(0xffFFFFFF);
  static const Color COLOR_QUARTZ = Color(0xffFBFAFD);
  static const Color COLOR_BACKGROUND = Color(0xffF7F6FB);
  static const Color COLOR_REGISTRATION_IMAGE_BACK = Color(0xffF9F6FF);
  static const Color COLOR_REGISTRATION_BACKGROUND = Color(0xffFBFAFF);
  static const Color COLOR_YELLOW_SEA = Color(0xffF5963E);
  static const Color COLOR_CARROT_ORANGE = Color(0xffF27E25);
  static const Color COLOR_NEON_CARROT = Color(0xffFF913A);
  static const Color COLOR_ALIZARIN = Color(0xffF22C2C);
  static const Color COLOR_CARIBBEAN_GREEN = Color(0xff04D49E);
  static const Color COLOR_SHAMROCK = Color(0xff4AD4A3);
  static const Color COLOR_LIME_GREEM = Color(0xff53D630);
  static const Color COLOR_LIME_GREEM1 = Color(0xff319784);
  static const Color COLOR_BRIGHT_TURQUOISE = Color(0xff25DDF2);
  static const Color COLOR_MEDIUM_VIOLET_RED = Color(0xffE41397);
  static const Color COLOR_WILD_WATERMELON = Color(0xffFF6580);
  static const Color COLOR_DARK_ORCHID = Color(0xffA42AC3);
}
